backend:
  name: git-gateway
  branch: main
collections:
  - name: routes
    label: Pages
    folder: src/routes
    create: true
    fields:
      - name: title
        label: "Titre"
      - name: label
        label: "Section"
      - label: "Paneau images"
        name: sideImages
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - name: body
        widget: markdown
  - name: galeries
    label: Galerie
    folder: src/galeries
    create: true
    fields:
      - name: title
        label: "Titre"
      - name: folderName
        label: "dossier"
    media_folder: 'static/uploads/galerie/{{fields.folderName}}'
    public_folder: '/uploads/uploads/galerie/{{fields.folderName}}'
media_folder: "static/uploads"
public_folder: "/uploads"
locale: 'fr'

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
